𝚜𝚜𝚑 ⎯𝚕 𝚐𝚖𝚊𝚗𝚣𝚘𝚗𝚒 ⎯𝙻𝟾𝟾𝟿𝟸:𝚍𝚋𝟶𝟸.𝚙𝚊𝚞.𝚙𝚒𝚌.𝚎𝚜:𝟻𝟺𝟹𝟸 𝚞𝚒.𝚙𝚒𝚌.𝚎𝚜

In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
import sqlalchemy as sqla
import pandas as pd
matplotlib.rcParams.update({'font.size': 15})

In [2]:
dsn = 'postgresql://readonly:PAUsc1ence@localhost:8892/dm'
engine = sqla.create_engine(dsn)

In [3]:
s = "SELECT 'id', 'input_production', 'pipeline', 'release', 'software_version', 'job_id', 'created' FROM paudm.production"
data = pd.read_sql(s,engine)

In [4]:
data.columns.values

array([u'?column?', u'?column?', u'?column?', u'?column?', u'?column?',
       u'?column?', u'?column?'], dtype=object)

In [9]:
data

,?column?,?column?,?column?,?column?,?column?,?column?,?column?
0,id,input_production,pipeline,release,software_version,job_id,created
1,id,input_production,pipeline,release,software_version,job_id,created
2,id,input_production,pipeline,release,software_version,job_id,created
3,id,input_production,pipeline,release,software_version,job_id,created
4,id,input_production,pipeline,release,software_version,job_id,created
5,id,input_production,pipeline,release,software_version,job_id,created
6,id,input_production,pipeline,release,software_version,job_id,created
7,id,input_production,pipeline,release,software_version,job_id,created
8,id,input_production,pipeline,release,software_version,job_id,created
9,id,input_production,pipeline,release,software_version,job_id,created
10,id,input_production,pipeline,release,software_version,job_id,created
11,id,input_production,pipeline,release,software_version,job_id,created
12,id,input_production,pipeline,release,software_version,job_id,created
13,id,input_production,pipeline,release,software_version,job_id,created
14,id,input_production,pipeline,release,software_version,job_id,created
15,id,input_production,pipeline,release,software_version,job_id,created
16,id,input_production,pipeline,release,software_version,job_id,created
17,id,input_production,pipeline,release,software_version,job_id,created
18,id,input_production,pipeline,release,software_version,job_id,created
19,id,input_production,pipeline,release,software_version,job_id,created
20,id,input_production,pipeline,release,software_version,job_id,created
21,id,input_production,pipeline,release,software_version,job_id,created
22,id,input_production,pipeline,release,software_version,job_id,created
23,id,input_production,pipeline,release,software_version,job_id,created
24,id,input_production,pipeline,release,software_version,job_id,created
25,id,input_production,pipeline,release,software_version,job_id,created
26,id,input_production,pipeline,release,software_version,job_id,created
27,id,input_production,pipeline,release,software_version,job_id,created
28,id,input_production,pipeline,release,software_version,job_id,created
29,id,input_production,pipeline,release,software_version,job_id,created
...,...,...,...,...,...,...,...
114,id,input_production,pipeline,release,software_version,job_id,created
115,id,input_production,pipeline,release,software_version,job_id,created
116,id,input_production,pipeline,release,software_version,job_id,created
117,id,input_production,pipeline,release,software_version,job_id,created
118,id,input_production,pipeline,release,software_version,job_id,created
119,id,input_production,pipeline,release,software_version,job_id,created
120,id,input_production,pipeline,release,software_version,job_id,created
121,id,input_production,pipeline,release,software_version,job_id,created
122,id,input_production,pipeline,release,software_version,job_id,created
123,id,input_production,pipeline,release,software_version,job_id,created
124,id,input_production,pipeline,release,software_version,job_id,created
125,id,input_production,pipeline,release,software_version,job_id,created
126,id,input_production,pipeline,release,software_version,job_id,created
127,id,input_production,pipeline,release,software_version,job_id,created
128,id,input_production,pipeline,release,software_version,job_id,created
129,id,input_production,pipeline,release,software_version,job_id,created
130,id,input_production,pipeline,release,software_version,job_id,created
131,id,input_production,pipeline,release,software_version,job_id,created
132,id,input_production,pipeline,release,software_version,job_id,created
133,id,input_production,pipeline,release,software_version,job_id,created
134,id,input_production,pipeline,release,software_version,job_id,created
135,id,input_production,pipeline,release,software_version,job_id,created
136,id,input_production,pipeline,release,software_version,job_id,created
137,id,input_production,pipeline,release,software_version,job_id,created
138,id,input_production,pipeline,release,software_version,job_id,created
139,id,input_production,pipeline,release,software_version,job_id,created
140,id,input_production,pipeline,release,software_version,job_id,created
141,id,input_production,pipeline,release,software_version,job_id,created
142,id,input_production,pipeline,release,software_version,job_id,created
143,id,input_production,pipeline,release,software_version,job_id,created

In [6]:
pd.read_csv("2283.csv",sep=',',comment='#',na_values='\N')

,id,input_production,pipeline,release,software_version,job_id,created
0,46,40.0,memba,PAU2015A_fpSD01,0.0.2,25696.0,NaN
1,294,292.0,memba,16A-CM292-CM294,0.0.2,267059.0,2016-10-29 00:16:58.685869
2,260,258.0,memba,16A-CM258-CM260,0.0.2,138050.0,2016-05-06 10:00:00
3,270,267.0,photoz,16A-CM258-CM267-P03-prior,0.0.1,151425.0,2016-06-10 14:20:30.695363
4,144,139.0,memba,PAU2015A_fpSD06,0.0.2,53056.0,2016-01-08 16:00:00
5,134,1.0,nightly,PAU2015A_03,0.4.0,42044.0,2015-12-02 18:00:00
6,184,139.0,memba,PAU2015A_fpDE09,0.0.2,63781.0,2016-02-21 20:00:00
7,286,258.0,memba,16A-CM258-CM286,0.0.2,222509.0,2016-09-19 09:33:32.635533
8,142,139.0,memba,PAU2015A_fpSD05,0.0.2,51348.0,2015-12-22 21:00:00
9,136,1.0,nightly,PAU2015A_04,0.4.0,44053.0,2015-12-16 21:00:00
10,188,139.0,memba,PAU2015A_fpSD11,0.0.2,67784.0,2016-03-04 19:00:00
11,194,139.0,memba,PAU2015A_fpSD13,0.0.2,75667.0,2016-03-15 09:00:00
12,240,NaN,register,201604-W3,0.4.0,84681.0,2016-06-18 10:00:00
13,288,285.0,memba,16A-CM285-CM288,0.0.2,235018.0,2016-09-22 16:08:52.784181
14,182,139.0,memba,PAU2015A_fpSD09,0.0.2,60356.0,2016-02-17 11:00:00
15,244,241.0,memba,PAU2016A_SDW3,0.0.2,87310.0,2016-06-18 10:00:00
16,138,136.0,memba,PAU2015A_fpCF06p,0.0.2,45990.0,2015-12-16 21:00:00
17,248,247.0,nightly,201604-CM,0.4.1,102519.0,2016-06-19 10:00:00
18,190,139.0,memba,PAU2015A_fpSD12,0.0.2,70616.0,2016-03-10 10:00:00
19,250,248.0,memba,PAU2016A_fpCM02,0.0.2,108748.0,2016-06-19 10:00:00
20,178,139.0,memba,PAU2015A_fpSD07,0.0.2,55319.0,2016-01-28 18:00:00
21,290,285.0,memba,16A-CM285-CM290,0.0.2,247523.0,2016-10-24 14:49:53.659077
22,252,247.0,nightly,201604-CM2,0.4.1,115343.0,2016-04-29 10:00:00
23,262,259.0,photoz,16A-CM6-SD01-P01,0.0.1,145149.0,2016-05-10 15:31:44.720254
24,42,40.0,memba,PAU2015A_fpCF04,0.0.1,22370.0,NaN
25,254,247.0,nightly,201604-CM4,0.4.1,116910.0,2016-05-03 10:00:00
26,268,260.0,photoz,16A-CM258-CM260-P02-prior,0.0.1,151367.0,2016-06-10 08:41:15.990949
27,256,254.0,memba,2016A-CM-CM01,0.0.2,124023.0,2016-05-04 09:00:00
28,180,139.0,memba,PAU2015A_fpSD08,0.0.2,57550.0,2016-02-16 18:00:00
29,272,258.0,memba,16A-CM258-CM272,0.0.2,152750.0,2016-06-27 13:25:23.642295
...,...,...,...,...,...,...,...
107,273,258.0,memba,16A-CM258-CM273,0.0.2,153994.0,2016-06-27 17:23:41.788569
108,287,285.0,memba,16A-CM285-CM287,0.0.2,228759.0,2016-09-19 11:31:43.192065
109,193,139.0,memba,PAU2015A_fpDE14,0.0.2,73955.0,2016-03-15 09:00:00
110,241,240.0,nightly,201604-W3,0.4.1,85569.0,2016-06-18 10:00:00
111,289,285.0,memba,16A-CM285-CM289,0.0.2,241265.0,2016-09-26 17:18:20.974898
112,249,248.0,memba,PAU2016A_fpCM01,0.0.2,103304.0,2016-06-19 10:00:00
113,251,247.0,nightly,201604-CM-astro,0.4.1,114192.0,2016-06-19 10:00:00
114,291,285.0,memba,16A-CM285-CM291,0.0.2,253773.0,2016-10-24 17:32:03.663891
115,253,247.0,nightly,201604-CM3,0.4.1,116126.0,2016-05-02 10:00:00
116,255,254.0,memba,2016A-CM-SD01,0.0.2,117694.0,2016-05-03 19:00:00
117,257,247.0,nightly,201604-CM5,0.4.1,130277.0,2016-05-05 10:00:00
118,285,247.0,nightly,201604-CM8,0.4.1,221726.0,2016-09-16 15:12:16.445227
119,297,292.0,memba,16A-CM285-CM297,0.0.2,285810.0,2016-11-01 12:18:24.99766
120,299,1.0,nightly,AutoNightly_R01,0.4.1,292898.0,2016-11-16 18:47:30.190313
121,471,468.0,memba,16B-R05-CM02,0.0.2,351879.0,2017-03-07 17:33:15.729616
122,631,468.0,memba,16B-R05-CM03,0.0.2,375457.0,2017-05-10 17:37:36.651106
123,323,1.0,nightly,AutoNightly_R03,0.4.1,300275.0,2016-11-27 01:52:43.534566
124,457,323.0,memba,16B-ANR03-CM01,0.0.2,317777.0,2017-01-16 12:20:39.956932
125,683,1.0,nightly,NightlyR07,0.4.1,414176.0,2017-07-26 16:52:56.355923
126,679,678.0,memba,17A-R06-CM01,0.0.2,398650.0,2017-06-01 15:43:11.007309
127,685,680.0,memba,17A-R06-CM02,0.0.2,416381.0,2017-07-30 22:06:20.902212
128,467,460.0,memba,16B-R04-CM01,0.0.2,330410.0,2017-02-16 17:39:38.29766
129,469,468.0,memba,16B-R05-CM01,0.0.2,341769.0,2017-02-20 11:42:54.450918
130,687,680.0,memba,17A-R06-CM04,0.0.2,443898.0,2017-09-08 23:07:23.495118
131,689,680.0,memba,17A-R06-CM06,0.0.2,471411.0,2017-09-13 16:53:28.330275
132,691,680.0,memba,17A-R06-CM08,0.0.2,498941.0,2017-11-06 17:51:05.563187
133,693,680.0,memba,17A-R06-CM10,0.0.2,526456.0,2017-11-10 16:58:37.726242
134,695,680.0,memba,17A-R06-CM12,0.0.2,553923.0,2017-11-13 18:06:44.334254
135,697,680.0,memba,17A-R06-CM14,0.0.2,581439.0,2017-11-15 07:30:40.765634
136,699,680.0,memba,17A-R06-CM16,0.0.2,608957.0,2017-11-21 00:33:27.074084

In [12]:
pd.read_csv('2282_production.csv',sep=',',comment='#',na_values='\N')

CParserError: Error tokenizing data. C error: Expected 8 fields in line 17, saw 10